import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import { MainLayout } from "@/components/layouts";
import "@/styles/tailwind.css";
import "@/styles/app.css";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Jewelry Shop",
  description: "Generated by create next app",
  authors: [
    { name: "Abdul Kader", url: "https://github.com/abdulkader789" },
    { name: "Md Mahi Kaishar", url: "mahikaishar@gmail.com" },
    { name: "", url: "" },
  ]
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={"inter.className"}>
        <MainLayout>
          {children}
        </MainLayout>
      </body>
    </html>
  );
}
