import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "@/styles/tailwind.css";
import "@/styles/app.css";
import "@/styles/font.css";
import { Footer, NavBar } from "@/components/common";
import Sidebar from "@/components/common/NavBar/Sidebar";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Jewelry Shop",
  description: "Generated by create next app",
  authors: [
    { name: "Abdul Kader", url: "https://github.com/abdulkader789" },
    { name: "Md Mahi Kaishar", url: "mahikaishar@gmail.com" },
    { name: "Toufiq Gilani Rabbu", url: "https://github.com/GilaniRabbu" },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={"inter.className"}>
        <NavBar />
        <Sidebar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
